/* ── music_demo.c — continuous-music NES starter ────────────────
 *
 * Bundled-driver demo: FamiTone2 (Shiru, public domain) plays a multi-
 * channel music track from ROM. Compare to `default.c` (silent) or
 * `hello_sprite.c` (single APU beep on button press).
 *
 * What ships:
 *   famitone2.s         — the 6502 music engine (~1.5 KB of code)
 *   famitone_bridge.s   — tiny C-callable wrappers around its entry pts
 *   music_data.s        — the song bytes (a public-domain test track)
 *
 * How it works:
 *   1. famitone_init(music_data) at boot — wires the song pointer
 *      and resets APU channel state.
 *   2. famitone_play(0) starts subsong 0. The track ships with two
 *      subsongs (0 + 1); change the index to switch.
 *   3. famitone_update() runs once per frame, right after the
 *      ppu_wait_nmi() heartbeat. This is the engine's tick — it
 *      walks the pattern data, computes envelope values, and writes
 *      the APU registers.
 *
 * APU sharing: this driver "owns" $4000-$4007 (pulse 1+2),
 * $4008-$400B (triangle), $400C-$400F (noise) while it's running.
 * If you want SFX too, swap in famitone2's SFX mode (FT_SFX_ENABLE
 * in famitone2.s) and call its sfx APIs from C via a similar bridge.
 *
 * To swap the song:
 *   - Export your FamiTracker module as .txt
 *   - Run text2data on it (see LICENSE-FAMITONE for the source repo)
 *   - Paste the generated bytes into music_data.s (keep the label).
 */

#include "nes_runtime.h"

/* Imported from famitone_bridge.s (the cc65-fastcall wrappers around
 * the asm engine). */
void __fastcall__ famitone_init(const unsigned char *music_data);
void __fastcall__ famitone_play(unsigned char song_index);
void __fastcall__ famitone_update(void);

/* music_data lives in music_data.s. */
extern const unsigned char music_data[];

static const unsigned char bg_colors[4] = { 0x0F, 0x01, 0x21, 0x31 };

/* Two BG tiles so the backdrop isn't a single flat colour (a uniform
 * screen reads >=92% one colour and fails the blank-screen check):
 *   tile 1 — solid colour 1
 *   tile 2 — solid colour 2
 * We checkerboard them across the nametable below. NES BG fetches from
 * $1000-$1FFF under the default PPUCTRL (bit 4 set), so BG tiles upload
 * there. */
static const unsigned char bg_tiles[2 * 16] = {
  /* tile 1: solid colour 1 (plane 0 all set, plane 1 clear) */
  0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  /* tile 2: solid colour 2 (plane 1 all set, plane 0 clear) */
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,
};

/* Fill nametable 0 ($2000) with a checkerboard of tiles 1 and 2 so the
 * screen shows two distinct colours. Attribute table left at palette 0.
 * Caller must have the PPU off. */
static void fill_bg(void) {
  unsigned int addr;
  unsigned char y, x;
  for (y = 0; y < 30; y++) {
    addr = 0x2000 + (unsigned int)y * 32;
    for (x = 0; x < 32; x++) {
      vram_unsafe_set(addr, (unsigned char)(((x ^ y) & 1) + 1));
      ++addr;
    }
  }
}

void main(void) {
  unsigned char palette[32];
  unsigned char i;
  unsigned char shade = 0;
  unsigned char frame = 0;

  for (i = 0; i < 32; i++) palette[i] = bg_colors[0];
  /* BG palette 0: backdrop black, colour 1 blue, colour 2 red — gives the
   * checkerboard two visibly different cells. */
  palette[0] = 0x0F;   /* $3F00 backdrop */
  palette[1] = 0x11;   /* colour 1 — blue */
  palette[2] = 0x16;   /* colour 2 — red  */

  ppu_off();
  palette_load(palette);
  /* Upload the two BG tiles to the BG pattern table at $1000. */
  chr_ram_upload(0x1000, bg_tiles, sizeof(bg_tiles));
  /* Paint the checkerboard backdrop so the screen is visibly NOT blank. */
  fill_bg();
  oam_clear();

  /* Start the music BEFORE rendering — FamiToneInit takes a few
   * hundred cycles, but it disables NMI internally only via APU regs;
   * the PPU is unaffected. Safe to call with PPU off. */
  famitone_init(music_data);
  famitone_play(0);

  ppu_on_all();

  for (;;) {
    ppu_wait_nmi();
    /* Drive the music engine once per frame. FamiTone2's docs call
     * for invocation from the NMI itself; calling it here (right
     * after the NMI returns) is equivalent for music-only use and
     * keeps the engine out of the vblank-critical path. */
    famitone_update();

    ++frame;
    if ((frame & 0x1F) == 0) {       /* every 32 frames */
      shade = (unsigned char)((shade + 1) & 0x03);
      vram_set(0x3F00, bg_colors[shade]);
    }
  }
}
