/* ── music_demo.c — continuous-music NES starter ────────────────
 *
 * Bundled-driver demo: FamiTone2 (Shiru, public domain) plays a multi-
 * channel music track from ROM. Compare to `default.c` (silent) or
 * `hello_sprite.c` (single APU beep on button press).
 *
 * What ships:
 *   famitone2.s         — the 6502 music engine (~1.5 KB of code)
 *   famitone_bridge.s   — tiny C-callable wrappers around its entry pts
 *   music_data.s        — the song bytes (a public-domain test track)
 *
 * How it works:
 *   1. famitone_init(music_data) at boot — wires the song pointer
 *      and resets APU channel state.
 *   2. famitone_play(0) starts subsong 0. The track ships with two
 *      subsongs (0 + 1); change the index to switch.
 *   3. famitone_update() runs once per frame, right after the
 *      ppu_wait_nmi() heartbeat. This is the engine's tick — it
 *      walks the pattern data, computes envelope values, and writes
 *      the APU registers.
 *
 * APU sharing: this driver "owns" $4000-$4007 (pulse 1+2),
 * $4008-$400B (triangle), $400C-$400F (noise) while it's running.
 * If you want SFX too, swap in famitone2's SFX mode (FT_SFX_ENABLE
 * in famitone2.s) and call its sfx APIs from C via a similar bridge.
 *
 * To swap the song:
 *   - Export your FamiTracker module as .txt
 *   - Run text2data on it (see LICENSE-FAMITONE for the source repo)
 *   - Paste the generated bytes into music_data.s (keep the label).
 */

#include "nes_runtime.h"

/* Imported from famitone_bridge.s (the cc65-fastcall wrappers around
 * the asm engine). */
void __fastcall__ famitone_init(const unsigned char *music_data);
void __fastcall__ famitone_play(unsigned char song_index);
void __fastcall__ famitone_update(void);

/* music_data lives in music_data.s. */
extern const unsigned char music_data[];

static const unsigned char bg_colors[4] = { 0x0F, 0x01, 0x21, 0x31 };

void main(void) {
  unsigned char palette[32];
  unsigned char i;
  unsigned char shade = 0;
  unsigned char frame = 0;

  for (i = 0; i < 32; i++) palette[i] = bg_colors[0];

  ppu_off();
  palette_load(palette);
  oam_clear();

  /* Start the music BEFORE rendering — FamiToneInit takes a few
   * hundred cycles, but it disables NMI internally only via APU regs;
   * the PPU is unaffected. Safe to call with PPU off. */
  famitone_init(music_data);
  famitone_play(0);

  ppu_on_all();

  for (;;) {
    ppu_wait_nmi();
    /* Drive the music engine once per frame. FamiTone2's docs call
     * for invocation from the NMI itself; calling it here (right
     * after the NMI returns) is equivalent for music-only use and
     * keeps the engine out of the vblank-critical path. */
    famitone_update();

    ++frame;
    if ((frame & 0x1F) == 0) {       /* every 32 frames */
      shade = (unsigned char)((shade + 1) & 0x03);
      vram_set(0x3F00, bg_colors[shade]);
    }
  }
}
