// GB/GBC song compiler — a note/duration song → the hUGEDriver `huge_song_t`
// C data the bundled driver (lib/c/hUGEDriver.c) plays.
//
// NOT a port of hUGETracker's converter (its .uge path is entangled with GB
// Studio); this targets OUR bundled hUGEDriver + its compact source format
// (lib/c/song_data.c). The driver reads, per channel, an array of 16-row
// patterns; each row is huge_row_t = { note, flags }:
//   note  = 0..71 (C3..B8), an index into hUGEDriver's hUGE_note_table.
//           C3=0, C4=12, A4=21, C5=24 … (octave*12 + semitone, base C3).
//   flags = 0 (re-trigger) | 0x80 (sustain — leave the APU alone)
//           note 0xFF = rest (silence the channel).
// A song = ticks_per_row + up to 4 channels, each { orders[], order_cnt, 1 }.
//
// Input mirrors the other romdev song compilers but is multi-channel:
//   { ticksPerRow?, channels: [ { rows: [ "C4"|{note}|"-"(sustain)|"."(rest) ] }, ... ] }
// Rows are flattened into 16-row patterns automatically; channels may differ in
// length (each loops independently, like the driver).

/** Semitone within an octave, C=0. */
const NOTE_BASE = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };

export const HUGE_ROWS_PER_PATTERN = 16;
const REST = 0xff;

/**
 * Note name → hUGE note index (C3 = 0, so index = (octave-3)*12 + semitone).
 * Range is 0..71 (C3..B8). Throws if out of range.
 * @param {string} name  e.g. "C4", "A#3", "Gb5"
 * @returns {number} 0..71
 */
export function noteToHugeIndex(name) {
  const m = /^([A-Ga-g])([#b-]?)(-?\d+)$/.exec(String(name).trim());
  if (!m) throw new Error(`GB song: bad note name "${name}" (expected like "C4", "A#3").`);
  let semi = NOTE_BASE[m[1].toUpperCase()];
  if (m[2] === '#') semi += 1;
  else if (m[2] === 'b') semi -= 1;
  const octave = parseInt(m[3], 10);
  const idx = (octave - 3) * 12 + semi;
  if (idx < 0 || idx > 71) throw new Error(`GB song: note "${name}" (index ${idx}) out of hUGE range C3..B8 (0..71).`);
  return idx;
}

/**
 * Resolve one row token to { note, flags }.
 *   "C4" / {note:"C4"} → trigger that note
 *   "-" / "_" / {sustain:true} → sustain (0x80)
 *   "." / "rest" / null / {rest:true} → rest (note 0xFF)
 * @param {string|object|null} tok
 * @returns {{note:number, flags:number}}
 */
function resolveRow(tok) {
  if (tok == null) return { note: REST, flags: 0 };
  if (typeof tok === 'object') {
    if (tok.rest) return { note: REST, flags: 0 };
    if (tok.sustain) return { note: 0, flags: 0x80 };
    if (tok.note != null) return { note: typeof tok.note === 'number' ? tok.note : noteToHugeIndex(tok.note), flags: 0 };
    return { note: REST, flags: 0 };
  }
  const s = String(tok).trim();
  if (s === '-' || s === '_' || s === '~') return { note: 0, flags: 0x80 };       // sustain
  if (s === '.' || s === '' || s.toLowerCase() === 'rest') return { note: REST, flags: 0 }; // rest
  return { note: noteToHugeIndex(s), flags: 0 };
}

const hex2 = (n) => '0x' + (n & 0xff).toString(16).padStart(2, '0').toUpperCase();

/**
 * Compile a multi-channel song to hUGEDriver C source + raw bytes.
 *
 * @param {object} song
 * @param {number} [song.ticksPerRow=8]  hUGE_dosound calls per row.
 * @param {Array<{rows: Array}>} song.channels  1..4 channels (CH1 sq, CH2 sq,
 *   CH3 wave, CH4 noise). Each `rows` is the note token list; it's padded to a
 *   multiple of 16 (with sustains) and split into 16-row patterns.
 * @param {string} [song.name="song"]  C identifier base (emits `<name>` huge_song_t).
 * @returns {{ bytes: Uint8Array, cSource: string, rows: number, channels: number }}
 *   bytes = patterns concatenated per channel, 2 bytes/row [note, flags];
 *   cSource = the full song_data.c-style C block (drop-in for song_data.c).
 */
export function compileSong(song) {
  if (!song || !Array.isArray(song.channels) || song.channels.length === 0) {
    throw new Error('GB song: expected { channels: [ { rows:[...] }, ... ] } (1..4 channels).');
  }
  if (song.channels.length > 4) throw new Error('GB song: at most 4 channels (CH1..CH4).');
  const ticksPerRow = song.ticksPerRow ?? 8;
  const name = song.name ?? 'song';
  const chPrefixes = ['ch1', 'ch2', 'ch3', 'ch4'];

  const allBytes = [];
  const cParts = [
    '/* generated by romdev encodeAudio({target:"gb"}) — hUGEDriver song data */',
    '#include "hUGEDriver.h"',
    '',
  ];
  /** per-channel descriptor lines for the huge_song_t */
  const chanDescriptors = ['{ 0, 0, 0 }', '{ 0, 0, 0 }', '{ 0, 0, 0 }', '{ 0, 0, 0 }'];
  let totalRows = 0;

  song.channels.forEach((ch, ci) => {
    const pfx = chPrefixes[ci];
    const rows = (ch.rows || []).map(resolveRow);
    if (rows.length === 0) return;
    // Pad to a whole number of 16-row patterns (pad with sustains so the tail holds).
    while (rows.length % HUGE_ROWS_PER_PATTERN !== 0) rows.push({ note: 0, flags: 0x80 });
    const nPat = rows.length / HUGE_ROWS_PER_PATTERN;
    totalRows = Math.max(totalRows, rows.length);

    const patNames = [];
    for (let p = 0; p < nPat; p++) {
      const patName = `${pfx}_p${p}`;
      patNames.push(patName);
      const slice = rows.slice(p * HUGE_ROWS_PER_PATTERN, (p + 1) * HUGE_ROWS_PER_PATTERN);
      const lines = slice.map((r) => `  { ${hex2(r.note)}, ${hex2(r.flags)} }`);
      cParts.push(`static const huge_row_t ${patName}[HUGE_ROWS_PER_PATTERN] = {\n${lines.join(',\n')}\n};`);
      for (const r of slice) allBytes.push(r.note & 0xff, r.flags & 0xff);
    }
    cParts.push(`static const huge_row_t * const ${pfx}_orders[] = { ${patNames.join(', ')} };`, '');
    chanDescriptors[ci] = `{ ${pfx}_orders, ${nPat}, 1 }`;
  });

  cParts.push(
    `const huge_song_t ${name} = {`,
    `  /* ticks_per_row */ ${ticksPerRow},`,
    `  /* ch1 */ ${chanDescriptors[0]},`,
    `  /* ch2 */ ${chanDescriptors[1]},`,
    `  /* ch3 */ ${chanDescriptors[2]},`,
    `  /* ch4 */ ${chanDescriptors[3]},`,
    `};`,
    ''
  );

  return {
    bytes: new Uint8Array(allBytes),
    cSource: cParts.join('\n'),
    rows: totalRows,
    channels: song.channels.length,
  };
}

export default compileSong;
