#!/usr/bin/env bash
# Build SDCC 4.4.0 → WASM. Two-pass: native build first to produce the Z80
# runtime libraries, then emscripten build to produce sdcc.wasm + sdas{z80,
# gb}.wasm + sdld.wasm. Stages everything under src/toolchains/sdcc/.
#
# Why 4.4.0 not 4.5.0: 4.5.0 was originally reported to have a z80-backend
# regression in `cheapMove → emit2` that hit `dbuf_append_str(NULL)` on
# `__sfr __at` access + function calls with arguments. We later (2026-05-25)
# found that the same assertion path was being triggered by emscripten stack
# overflow (default 64 KB) corrupting `sm83_regs[]` — fixed in _lib.sh with
# `-s STACK_SIZE=8388608`. 4.5.0 hasn't been re-tested with the stack fix;
# 4.4.0 is the verified-working version. When testing 4.5.0 again, do it
# with the new STACK_SIZE flag in place. When upstream ships 4.6.0, bump.
#
# Targets enabled: z80, z180, gbz80 (SM83 / Game Boy), ez80_z80. Every
# other backend (mcs51, pic*, hc08, stm8, mos6502, etc.) is disabled —
# we have no cores that need them, and disabling them halves the build.
#
# Inspired by sehugg/8bitworkshop-compilers' SDCC recipe, but adapted to
# our Node-MEMFS pattern: runtime headers/libs ship as plain files under
# share/sdcc/ and get mounted into MEMFS at call time by sdcc.js
# (matches the cc65 wrapper layout).
set -euo pipefail
. "$(dirname "$0")/_lib.sh"
require_cmd emcc
require_cmd curl
require_cmd tar
require_cmd make

SDCC_VERSION="4.4.0"
SDCC_TARBALL="sdcc-src-${SDCC_VERSION}.tar.bz2"
SDCC_URL="https://downloads.sourceforge.net/project/sdcc/sdcc/${SDCC_VERSION}/${SDCC_TARBALL}"
SDCC_BUILD_DIR="$BUILD_DIR/sdcc"
SDCC_SRC_DIR="$SDCC_BUILD_DIR/sdcc-${SDCC_VERSION}"
OUT="$PROJECT_DIR/src/toolchains/sdcc/wasm"
SHARE="$PROJECT_DIR/src/toolchains/sdcc/share/sdcc"

SDCC_CONFIG_PORTS=(
  --enable-z80-port
  --enable-z180-port
  --enable-gbz80-port
  --enable-ez80_z80-port
  --disable-mcs51-port
  --disable-r2k-port
  --disable-r3ka-port
  --disable-tlcs90-port
  --disable-ds390-port
  --disable-ds400-port
  --disable-pic14-port
  --disable-pic16-port
  --disable-hc08-port
  --disable-s08-port
  --disable-stm8-port
  --disable-pdk13-port
  --disable-pdk14-port
  --disable-pdk15-port
  --disable-pdk16-port
  --disable-mos6502-port
  --disable-doc
  --disable-libgc
)

# Disable subprojects we don't need bundled in WASM:
# - ucsim: simulator
# - packihx: standalone Intel HEX tool
# - sdcpp: SDCC's preprocessor binary (we use the built-in one)
# - sdcdb: debugger
# - sdbinutils: GNU binutils-style tools (we use sdas/sdld instead)
# device-lib stays ENABLED for the native pass (we need the .lib files) but
# DISABLED for the emscripten pass (we re-use the natively-built libs).
SDCC_EMCC_EXTRA_DISABLE=(
  --disable-ucsim
  --disable-device-lib
  --disable-packihx
  --disable-sdcdb
  --disable-sdbinutils
)
# sdcpp is REQUIRED: sdcc fork/exec's the preprocessor binary and emscripten
# can't fork. We build sdcpp to WASM and run it ourselves before sdcc.

# ---- step 1: download + extract ---------------------------------------------
mkdir -p "$SDCC_BUILD_DIR"
if [ ! -f "$SDCC_BUILD_DIR/$SDCC_TARBALL" ]; then
  echo "Downloading $SDCC_TARBALL ..."
  curl -L -o "$SDCC_BUILD_DIR/$SDCC_TARBALL" "$SDCC_URL"
fi

if [ ! -d "$SDCC_SRC_DIR" ]; then
  echo "Extracting $SDCC_TARBALL ..."
  tar -xjf "$SDCC_BUILD_DIR/$SDCC_TARBALL" -C "$SDCC_BUILD_DIR"
  # SDCC's tarball extracts to a directory called just "sdcc/" not "sdcc-X.Y.Z/".
  # Rename so we can have multiple versions side by side.
  if [ -d "$SDCC_BUILD_DIR/sdcc" ] && [ ! -d "$SDCC_SRC_DIR" ]; then
    mv "$SDCC_BUILD_DIR/sdcc" "$SDCC_SRC_DIR"
  fi
fi

# ---- step 2: native build (produces Z80 runtime libs) ----------------------
echo "Native pass: building sdcc + Z80 runtime libs ..."
cd "$SDCC_SRC_DIR"
if [ ! -f "$SDCC_SRC_DIR/.native-built" ]; then
  # SDCC 4.5.0's linker (sdas/linksrc/aslink.h) declares `elf()` with
  # empty parens — K&R "unspecified args" — but the definition takes an
  # int. GCC 14+ now treats empty parens as `(void)`, so the call site
  # `elf(i)` errors out. Patch the one bad declaration; doesn't affect
  # the emscripten pass (clang/emcc are more lenient anyway).
  sed -i 's/^\(extern[[:space:]]*VOID[[:space:]]*\)elf();/\1elf(int);/' \
    sdas/linksrc/aslink.h

  ./configure "${SDCC_CONFIG_PORTS[@]}"
  make -j"$(nproc)"
  touch "$SDCC_SRC_DIR/.native-built"
fi

# Stage the runtime libs + headers BEFORE the emscripten pass touches the tree.
# The native build leaves .lib files in device/lib/build/<port>/.
#
# IMPORTANT: SDCC's `device/include/` directory contains both the runtime
# headers we want AND build artifacts (Makefile, Makefile.in, *.mk, etc.)
# generated by `./configure`. The generated Makefile bakes in absolute
# paths to the build host's emcc — shipping it pollutes our runtime tree
# with the build user's $HOME. Filter to .h files only.
mkdir -p "$SHARE/include" "$SHARE/lib"
(cd device/include && find . -type d -exec mkdir -p "$SHARE/include/{}" \;)
(cd device/include && find . -type f -name "*.h" -exec cp --parents {} "$SHARE/include/" \;)
for port in z80 z180 sm83 gbz80 ez80_z80; do
  if [ -d "device/lib/build/$port" ]; then
    mkdir -p "$SHARE/lib/$port"
    # Same filter: ship only .lib + .rel runtime files, not generated
    # Makefiles or .o intermediates.
    (cd "device/lib/build/$port" && find . -type f \( -name "*.lib" -o -name "*.rel" \) -exec cp --parents {} "$SHARE/lib/$port/" \;)
  fi
done

# Defensive: strip any absolute-path leakage from any text-shaped file
# that might have snuck through. .h files shouldn't reference build host
# paths but check anyway — fail loudly if they do.
if grep -r "$(echo "$HOME" | sed 's/[\/&]/\\&/g')" "$SHARE/" 2>/dev/null | head -3; then
  echo "FATAL: build-host absolute path leaked into $SHARE/ — refusing to ship." >&2
  echo "Check what's in $SHARE and adjust the filter above." >&2
  exit 1
fi

# ---- step 3: emscripten build (the actual sdcc.wasm) -----------------------
echo "Emscripten pass: rebuilding sdcc.wasm + sdas{z80,gb}.wasm + sdld.wasm ..."
EMCC_LD_FLAGS="${EM_CLI_FLAGS[*]} -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s USE_BOOST_HEADERS=1 -s USE_ZLIB=1"
# Clean .o files from the native pass — they're for the host arch and will
# confuse the emscripten link.
make clean || true

# `-s USE_BOOST_HEADERS=1` makes emcc fetch & install the boost headers
# into its sysroot the first time it's invoked. We need them present
# during the configure preprocess test too, so do a no-op compile to
# trigger emcc's boost port install BEFORE configure runs its header
# probes. After this, `emcc -c -include boost/graph/adjacency_list.hpp`
# resolves cleanly through emcc's sysroot.
echo "Priming emcc boost port ..."
echo "#include <boost/graph/adjacency_list.hpp>" > /tmp/_boost_prime.cpp
echo "int main(){}" >> /tmp/_boost_prime.cpp
emcc -s USE_BOOST_HEADERS=1 -c /tmp/_boost_prime.cpp -o /tmp/_boost_prime.o
rm -f /tmp/_boost_prime.cpp /tmp/_boost_prime.o

# Same priming for the emscripten zlib port. SDCC's configure runs a
# `checking for zlib.h` probe; under emconfigure that probe compiles against
# emcc's *sysroot*, NOT /usr/include — so native zlib1g-dev does NOT satisfy
# it. `-s USE_ZLIB=1` makes emcc fetch + install its own zlib port into the
# sysroot; prime it with a no-op compile so zlib.h is present BEFORE the
# probe runs. (Previously this "worked" only because the build host's emcc
# happened to have libz.a cached from an earlier project — invisible on a
# clean machine / in the build container. The container caught it.)
echo "Priming emcc zlib port ..."
echo "#include <zlib.h>" > /tmp/_zlib_prime.c
echo "int main(){return 0;}" >> /tmp/_zlib_prime.c
emcc -s USE_ZLIB=1 /tmp/_zlib_prime.c -o /tmp/_zlib_prime.js
rm -f /tmp/_zlib_prime.c /tmp/_zlib_prime.js /tmp/_zlib_prime.wasm

emconfigure ./configure \
  --host=i686-pc-linux-gnu \
  --build=x86_64-pc-linux-gnu \
  "${SDCC_CONFIG_PORTS[@]}" \
  "${SDCC_EMCC_EXTRA_DISABLE[@]}" \
  CPPFLAGS="-s USE_BOOST_HEADERS=1 -s USE_ZLIB=1" \
  CXXFLAGS="-s USE_BOOST_HEADERS=1 -s USE_ZLIB=1" \
  EMCC_CFLAGS="-O2" \
  EMCC_LDFLAGS="$EMCC_LD_FLAGS"

# 8bitworkshop's known patch: backtrace_symbols_fd isn't usable under emscripten
# and SDCC's autoconf detection lies about it.
sed -i 's|#define HAVE_BACKTRACE_SYMBOLS_FD 1||g' sdccconf.h

# Build the main sdcc driver. The top-level Makefile under emmake also
# builds sdas/* and sdld/* (sdldz80, sdldgb) and stages them into bin/.
emmake make -j"$(nproc)" -C src \
  EMCC_CFLAGS="-O2 -s EXPORT_NAME=createSdcc" \
  LDFLAGS="$EMCC_LD_FLAGS -s EXPORT_NAME=createSdcc"

# Linker. sdld lives under sdas/linksrc in 4.5.0 (it's the same source as
# the per-port sdldz80/sdldgb/etc binaries in bin/).
emmake make -j"$(nproc)" -C sdas/linksrc \
  EMCC_CFLAGS="-O2 -s EXPORT_NAME=createSdldz80" \
  LDFLAGS="$EMCC_LD_FLAGS -s EXPORT_NAME=createSdldz80" \
  sdcc-ldz80 sdcc-ldgb || true

# Per-port assemblers — the top-level `make -C src` doesn't recurse into
# these in modern SDCC. Build them individually so bin/sdasz80(.wasm) +
# bin/sdasgb(.wasm) land in place. Each one is a distinct emscripten link.
emmake make -j"$(nproc)" -C sdas/asz80 \
  EMCC_CFLAGS="-O2 -s EXPORT_NAME=createSdasz80" \
  LDFLAGS="$EMCC_LD_FLAGS -s EXPORT_NAME=createSdasz80" || true
emmake make -j"$(nproc)" -C sdas/asgb \
  EMCC_CFLAGS="-O2 -s EXPORT_NAME=createSdasgb" \
  LDFLAGS="$EMCC_LD_FLAGS -s EXPORT_NAME=createSdasgb" || true

# sdcpp — SDCC's own preprocessor (support/cpp, a GCC-derived subproject).
# We do NOT use it: our wrapper (src/toolchains/sdcc/sdcc.js) preprocesses with
# mcpp.wasm (built by build-mcpp.sh) and feeds the .i to sdcc in --c1mode, so
# sdcc never invokes a preprocessor itself (Emscripten can't fork/exec). So
# this build is BEST-EFFORT (`|| true`) and its output is intentionally NOT
# staged — mcpp is the shipped preprocessor, not sdcpp.
#
# It's kept as a best-effort build only so that, if SDCC ever changes such that
# sdcpp becomes necessary, the recipe is already here. It currently fails to
# link under emcc 4.0.18 anyway (its bundled gcc needs sdbinutils/libiberty,
# which we --disable for the emscripten pass), which is fine precisely because
# we don't ship it. The -Wno-* flags work around a getexecname() portability
# error in its bundled libbacktrace (Solaris-only symbol; newer clang errors
# where older emcc warned) so it gets as far as it can.
#
# DO NOT add `-e`-style hard failure here and DO NOT add sdcpp to the staging
# verification — a sdcpp link failure must not fail the build. (Earlier this was
# briefly "fixed" to fail loudly based on a stale comment claiming sdcpp was
# required; it isn't. mcpp is.)
if [ -d support/cpp ]; then
  emmake make -j"$(nproc)" -C support/cpp \
    EMCC_CFLAGS="-O2 -Wno-implicit-function-declaration -Wno-int-conversion -s EXPORT_NAME=createSdcpp" \
    LDFLAGS="$EMCC_LD_FLAGS -s EXPORT_NAME=createSdcpp" || true
fi

# ---- step 4: stage the .wasm + .js artifacts -------------------------------
# Emscripten produces TWO files per link: <name> (JS glue) and <name>.wasm.
# SDCC's Makefile uses extension-less target names, so we copy the JS glue
# to <name>.js for our wrapper to import as ESM. Source locations:
#   - main driver: src/sdcc + src/sdcc.wasm
#   - assemblers/linkers: bin/sdas{z80,gb} + bin/sdld{z80,gb} (+ .wasm)
mkdir -p "$OUT"
# SDCC's link step writes <name> (JS glue) + <name>.wasm. For sdld, the
# Makefile builds bin/sdld + bin/sdld.wasm once, then cp's the JS to
# sdldz80/sdldgb without copying the .wasm — they all share sdld.wasm.
# We unify by staging sdld once and using it as the linker for every port
# (the JS glue is identical; per-port behavior is selected by CLI flags).
stage_tool() {
  local src_base="$1"
  local dst_name="$2"
  local wasm_src="${3:-${src_base}.wasm}"
  if [ -f "${src_base}" ] && [ -f "${wasm_src}" ]; then
    cp "${src_base}" "$OUT/${dst_name}.js"
    cp "${wasm_src}" "$OUT/${dst_name}.wasm"
    echo "staged ${dst_name}"
  else
    echo "(skipped: ${src_base} or ${wasm_src} not present)"
  fi
}

stage_tool src/sdcc sdcc
stage_tool bin/sdasz80 sdasz80
stage_tool bin/sdasgb sdasgb
# sdldgb / sdldz80 are sdld JS glue copies; the .wasm is sdld.wasm.
stage_tool bin/sdld sdld
stage_tool bin/sdcpp sdcpp

# Verify the driver landed — without sdcc.wasm the toolchain is useless.
# (The preprocessor is mcpp.wasm, staged by build-mcpp.sh, not sdcpp — see the
# sdcpp note above. sdasz80/sdasgb/sdld are checked by their stage_tool output.)
if [ ! -f "$OUT/sdcc.wasm" ]; then
  echo "FATAL: sdcc.wasm not produced. Check the emscripten link step." >&2
  exit 1
fi

echo
echo "SDCC ${SDCC_VERSION} WASM staged at $OUT"
echo "Runtime libs + headers staged at $SHARE"
ls -lh "$OUT"
