// sync32 PCM — WAV (or raw s16) → signed 16-bit mono at a rate that divides
// the console's 48 kHz ring evenly, plus the C array + defines a game's mixer
// needs. The console has no PCM channel: a game mixes samples into the ring
// itself, so the encoder's job is the rate decision and the bytes.
//
// Default 24 kHz: exactly half the ring rate, so playback is a zero-order hold
// (each sample twice) with no resampler in the mixer, at half the ROM cost of
// 48 kHz — the trade every port lands on once it sees the image budget.

import { parseWav, resampleLinear } from "../genesis/xgm2-pcm.js";

export const RING_RATE = 48000;

/**
 * @param {Uint8Array|Buffer} input
 * @param {{rate?: number, format?: "wav"|"pcm16", pcmRate?: number}} [opts]
 */
export function wavToSync32Pcm(input, opts = {}) {
  const rate = opts.rate ?? 24000;
  if (!Number.isInteger(rate) || rate < 4000 || rate > RING_RATE) throw new Error(`sync32 pcm: rate ${rate} must be 4000..48000`);
  if (RING_RATE % rate !== 0) throw new Error(`sync32 pcm: rate ${rate} does not divide the 48000 Hz ring evenly — use 48000, 24000, 16000, 12000, 9600, 8000 or 6000 so the mixer can hold each sample an integer number of frames`);
  let samples, sourceRate;
  if (opts.format === "pcm16") {
    const u = Buffer.from(input);
    const n = u.length >> 1;
    samples = new Float32Array(n);
    for (let i = 0; i < n; i++) samples[i] = u.readInt16LE(i * 2) / 32768;
    sourceRate = opts.pcmRate || 0;
    if (!sourceRate) throw new Error("sync32 pcm: raw pcm16 input needs `pcmRate` (the source sample rate in Hz).");
  } else {
    const parsed = parseWav(input);
    samples = parsed.samples;
    sourceRate = parsed.sampleRate;
  }
  const res = sourceRate === rate ? samples : resampleLinear(samples, sourceRate, rate);
  const pcm = new Int16Array(res.length);
  let peak = 0;
  for (let i = 0; i < res.length; i++) {
    let v = Math.round(res[i] * 32767);
    if (v > 32767) v = 32767; else if (v < -32768) v = -32768;
    pcm[i] = v; if (Math.abs(v) > peak) peak = Math.abs(v);
  }
  return { pcm, rate, sourceRate, sampleCount: pcm.length, bytes: pcm.length * 2, step: RING_RATE / rate, durationSeconds: pcm.length / rate, peak };
}

/** C source: the sample as int16_t[] + LEN/RATE/STEP defines. */
export function emitSync32PcmC(r, name) {
  const N = name.toUpperCase();
  const lines = [
    `/* sync32 PCM '${name}': s16 mono, ${r.rate} Hz, ${r.sampleCount} samples (${r.durationSeconds.toFixed(3)} s), ${r.bytes} bytes. Generated by romdev encodeAudio. */`,
    `/* Play by holding each sample ${N}_STEP ring frames (the ring is 48000 Hz); scale (>> 2 per slot) when mixing several. */`,
    `#include <stdint.h>`,
    `#define ${N}_LEN ${r.sampleCount}`,
    `#define ${N}_RATE ${r.rate}`,
    `#define ${N}_STEP ${r.step}`,
    `const int16_t ${name}[${r.sampleCount}] = {`,
  ];
  for (let i = 0; i < r.pcm.length; i += 16) lines.push("  " + Array.from(r.pcm.subarray(i, i + 16), String).join(", ") + ",");
  lines.push("};", "");
  return lines.join("\n");
}
