// iNES header + NROM linker-config synthesis for cc65/ca65 NES builds.
//
// The most common NES *reverse-engineering* build shape — rebuilding a
// commercial NROM game from its disassembly (e.g. SMBDIS) into a byte-identical
// `.nes` — needs three pieces of pure boilerplate that are identical for every
// NROM CHR-ROM cart:
//   1. the 16-byte iNES header (`.segment "HEADER"`),
//   2. a CHARS segment fed from the extracted CHR-ROM blob (`.incbin`),
//   3. a 3-region MEMORY/SEGMENTS .cfg concatenating HEADER + PRG + CHARS into
//      one output file.
//
// `build({inesHeader:{prgBanks, chrBanks, mapper, mirroring}})` and
// `disasm({target:'project'})` both use this so the agent never hand-derives
// header bytes or writes glue `.s`/`.cfg` files. Proven byte-identical against
// nestest.nes (NROM-128, 16K PRG + 8K CHR) and 32K-PRG NROM-256 carts.

/**
 * @typedef {Object} InesHeaderSpec
 * @property {number} prgBanks  - 16KB PRG-ROM banks (1 = NROM-128, 2 = NROM-256).
 * @property {number} [chrBanks] - 8KB CHR-ROM banks (0 = CHR-RAM, no CHARS). Default 0.
 * @property {number} [mapper]   - iNES mapper number. Default 0 (NROM).
 * @property {"horizontal"|"vertical"} [mirroring] - nametable mirroring. Default "horizontal".
 * @property {boolean} [battery] - PRG-RAM battery (flags6 bit 1). Default false.
 */

/**
 * Build the 16 raw iNES header bytes for a spec.
 * @param {InesHeaderSpec} spec
 * @returns {Uint8Array} exactly 16 bytes
 */
export function inesHeaderBytes(spec) {
  const prg = spec.prgBanks;
  const chr = spec.chrBanks ?? 0;
  const mapper = spec.mapper ?? 0;
  const mirroring = spec.mirroring ?? "horizontal";
  if (!Number.isInteger(prg) || prg < 1 || prg > 255) {
    throw new Error(`inesHeader.prgBanks must be an integer 1..255 (16KB each); got ${spec.prgBanks}`);
  }
  if (!Number.isInteger(chr) || chr < 0 || chr > 255) {
    throw new Error(`inesHeader.chrBanks must be an integer 0..255 (8KB each; 0 = CHR-RAM); got ${spec.chrBanks}`);
  }
  if (!Number.isInteger(mapper) || mapper < 0 || mapper > 255) {
    throw new Error(`inesHeader.mapper must be an integer 0..255; got ${spec.mapper}`);
  }
  if (mirroring !== "horizontal" && mirroring !== "vertical") {
    throw new Error(`inesHeader.mirroring must be "horizontal" or "vertical"; got ${JSON.stringify(spec.mirroring)}`);
  }
  const flags6 = (mirroring === "vertical" ? 0x01 : 0x00) | (spec.battery ? 0x02 : 0x00) | ((mapper & 0x0f) << 4);
  const flags7 = mapper & 0xf0;
  const h = new Uint8Array(16);
  h[0] = 0x4e; h[1] = 0x45; h[2] = 0x53; h[3] = 0x1a; // "NES\x1a"
  h[4] = prg;
  h[5] = chr;
  h[6] = flags6;
  h[7] = flags7;
  // bytes 8..15 stay 0 (iNES 1.0 padding)
  return h;
}

/**
 * ca65 source that emits the iNES header as `.segment "HEADER"`.
 * @param {InesHeaderSpec} spec
 * @returns {string}
 */
export function inesHeaderSource(spec) {
  const h = inesHeaderBytes(spec);
  const prg = spec.prgBanks;
  const chr = spec.chrBanks ?? 0;
  const mapper = spec.mapper ?? 0;
  const mirroring = spec.mirroring ?? "horizontal";
  const hex = (b) => "$" + b.toString(16).padStart(2, "0").toUpperCase();
  return [
    "; iNES header — auto-generated by build({inesHeader:{...}}).",
    `; prgBanks=${prg} (${prg * 16}KB)  chrBanks=${chr} (${chr * 8}KB${chr === 0 ? " = CHR-RAM" : ""})` +
      `  mapper=${mapper}  mirroring=${mirroring}`,
    '.segment "HEADER"',
    `        .byte ${hex(h[0])},${hex(h[1])},${hex(h[2])},${hex(h[3])}   ; "NES"+EOF`,
    `        .byte ${h[4]}                       ; PRG-ROM 16KB banks`,
    `        .byte ${h[5]}                       ; CHR-ROM 8KB banks${chr === 0 ? " (0 = CHR-RAM)" : ""}`,
    `        .byte ${hex(h[6])}                     ; flags6 (mapper lo nibble + mirroring${spec.battery ? " + battery" : ""})`,
    `        .byte ${hex(h[7])}                     ; flags7 (mapper hi nibble)`,
    "        .byte 0,0,0,0,0,0,0,0       ; padding (iNES 1.0)",
    "",
  ].join("\n");
}

/**
 * ca65 source that pulls the CHR-ROM blob into the CHARS segment.
 * @param {string} incbinName - the binaryInclude file name to `.incbin`.
 * @returns {string}
 */
export function charsSource(incbinName) {
  return [
    "; CHR-ROM data — auto-generated by build({inesHeader:{...}}).",
    '.segment "CHARS"',
    `        .incbin "${incbinName}"`,
    "",
  ].join("\n");
}

/**
 * A flat NROM linker .cfg: HEADER(16B) + PRG + (optional) CHARS, all concatenated
 * into one %O output file. "Flat" = one CODE segment carrying the whole PRG image
 * with its OWN embedded reset/NMI/IRQ vectors (the shape a disassembly produces),
 * NOT cc65's STARTUP/VECTORS/CONDES split. Use `chr-rom` (the named preset) for
 * cc65-C-with-segments builds instead.
 *
 *  - prgBanks=1 (NROM-128): the 16KB image maps at $C000 (mirrored to $8000).
 *  - prgBanks=2 (NROM-256): the 32KB image maps at $8000.
 *
 * @param {InesHeaderSpec} spec
 * @returns {string} ld65 config text
 */
export function nromFlatCfg(spec) {
  const prg = spec.prgBanks;
  const chr = spec.chrBanks ?? 0;
  const prgSize = prg * 0x4000;
  // NROM-128's single 16KB bank lives in the upper half so $FFFA vectors land;
  // anything larger fills from $8000 down.
  const prgStart = prg === 1 ? 0xc000 : 0x10000 - prgSize;
  const lines = [
    "# Flat NROM linker config — auto-generated by build({inesHeader:{...}}).",
    "# HEADER(16B) + PRG + " + (chr > 0 ? "CHARS(CHR-ROM)" : "(no CHARS — CHR-RAM)") +
      ", concatenated into one .nes.",
    "# 'Flat' CODE segment = the whole PRG image with its own embedded vectors",
    "# (disassembly shape). For cc65-C with segment split, use linkerConfig:'chr-rom'.",
    "MEMORY {",
    "    HEADER: file = %O, start = $0000, size = $0010, fill = yes;",
    `    PRG:    file = %O, start = $${prgStart.toString(16).toUpperCase()}, size = $${prgSize.toString(16).toUpperCase()}, fill = yes, fillval = $FF;`,
  ];
  if (chr > 0) {
    lines.push(`    CHARS:  file = %O, start = $0000, size = $${(chr * 0x2000).toString(16).toUpperCase()}, fill = yes;`);
  }
  lines.push(
    "}",
    "SEGMENTS {",
    "    HEADER: load = HEADER, type = ro;",
    "    CODE:   load = PRG,    type = ro;",
  );
  if (chr > 0) {
    lines.push("    CHARS:  load = CHARS,  type = ro;");
  }
  lines.push("}", "");
  return lines.join("\n");
}
