/* romdev: no-op stubs for ALL inactive video-plugin entry points (glide64/gln64/
   rice). angrylion is the active renderer; plugins.c's static tables reference
   these so they must resolve. int(...)=0 covers every table slot signature. */
int glide64ChangeWindow() { return 0; }
int glide64FBGetFrameBufferInfo() { return 0; }
int glide64FBRead() { return 0; }
int glide64FBWrite() { return 0; }
int glide64gDPLoadBlock() { return 0; }
int glide64gDPSetScissor() { return 0; }
int glide64gSPClipVertex() { return 0; }
int glide64gSPCombineMatrices() { return 0; }
int glide64gSPDlistCount() { return 0; }
int glide64gSPForceMatrix() { return 0; }
int glide64gSPLight() { return 0; }
int glide64gSPLightColor() { return 0; }
int glide64gSPLookAt() { return 0; }
int glide64gSPViewport() { return 0; }
int glide64InitiateGFX() { return 0; }
int glide64MoveScreen() { return 0; }
int glide64PluginGetVersion() { return 0; }
int glide64ProcessDList() { return 0; }
int glide64ProcessRDPList() { return 0; }
int glide64ReadScreen2() { return 0; }
int glide64RomClosed() { return 0; }
int glide64RomOpen() { return 0; }
int glide64SetRenderingCallback() { return 0; }
int glide64ShowCFB() { return 0; }
int glide64UpdateScreen() { return 0; }
int glide64ViStatusChanged() { return 0; }
int glide64ViWidthChanged() { return 0; }
int gln64ChangeWindow() { return 0; }
int gln64FBGetFrameBufferInfo() { return 0; }
int gln64FBRead() { return 0; }
int gln64FBWrite() { return 0; }
int gln64gDPLoadBlock() { return 0; }
int gln64gDPSetScissor() { return 0; }
int gln64gSPClipVertex() { return 0; }
int gln64gSPCombineMatrices() { return 0; }
int gln64gSPDlistCount() { return 0; }
int gln64gSPForceMatrix() { return 0; }
int gln64gSPLight() { return 0; }
int gln64gSPLightColor() { return 0; }
int gln64gSPLookAt() { return 0; }
int gln64gSPViewport() { return 0; }
int gln64InitiateGFX() { return 0; }
int gln64MoveScreen() { return 0; }
int gln64PluginGetVersion() { return 0; }
int gln64ProcessDList() { return 0; }
int gln64ProcessRDPList() { return 0; }
int gln64ReadScreen2() { return 0; }
int gln64RomClosed() { return 0; }
int gln64RomOpen() { return 0; }
int gln64SetRenderingCallback() { return 0; }
int gln64ShowCFB() { return 0; }
int gln64UpdateScreen() { return 0; }
int gln64ViStatusChanged() { return 0; }
int gln64ViWidthChanged() { return 0; }
int riceChangeWindow() { return 0; }
int riceFBGetFrameBufferInfo() { return 0; }
int riceFBRead() { return 0; }
int riceFBWrite() { return 0; }
int riceInitiateGFX() { return 0; }
int riceMoveScreen() { return 0; }
int ricePluginGetVersion() { return 0; }
int riceProcessDList() { return 0; }
int riceProcessRDPList() { return 0; }
int riceReadScreen2() { return 0; }
int riceRomClosed() { return 0; }
int riceRomOpen() { return 0; }
int riceSetRenderingCallback() { return 0; }
int riceShowCFB() { return 0; }
int riceUpdateScreen() { return 0; }
int riceViStatusChanged() { return 0; }
int riceViWidthChanged() { return 0; }
