// romdev-xgm2 — pure-JS VGM → XGM2 converter for Sega Genesis / Mega Drive.
//
// A faithful port of SGDK's `xgm2tool` (Java). Parses a .vgm (or gzipped .vgz)
// Mega Drive music log and emits a COMPILED XGM2 blob — the exact format SGDK's
// Z80 XGM2 driver plays via `XGM2_play()`. No Java, no jar, no native binary.
//
// Pipeline (mirrors xgm2tool's Launcher): new VGM(bytes) -> new XGM(vgm, packed)
// -> xgm.asByteArray().

import { gunzipSync } from "node:zlib";
import { VGM } from "./vgm.js";
import { XGM } from "./xgm.js";

/** A .vgz / gzip member starts with 0x1F 0x8B. */
function isGzip(bytes) {
  return bytes.length >= 2 && (bytes[0] & 0xff) === 0x1f && (bytes[1] & 0xff) === 0x8b;
}

/**
 * Convert a VGM (or gzipped VGZ) buffer to a compiled XGM2 blob.
 *
 * @param {Uint8Array|Buffer} vgmBytes  raw .vgm or gzipped .vgz contents
 * @param {Object} [opts]
 * @param {boolean} [opts.packed=true]  emit the COMPILED (Z80-ready) XGM2 blob
 *   (the `.xgc` form, what you .incbin into a ROM and play). false = the
 *   uncompiled `.xgm` form (rarely what you want for embedding).
 * @param {'ntsc'|'pal'|null} [opts.system=null]  force the timing flag (VGM
 *   offset 0x24): 'ntsc' = 60, 'pal' = 50. null leaves the VGM's own value.
 * @returns {Uint8Array}  the XGM2 blob
 */
export function vgmToXgm2(vgmBytes, opts = {}) {
  const { packed = true, system = null } = opts;
  let data = Uint8Array.from(isGzip(vgmBytes) ? gunzipSync(vgmBytes) : vgmBytes);

  // Force NTSC/PAL timing the same way xgm2tool's loadVGM does (byte 0x24).
  if (system === "ntsc") data[0x24] = 60;
  else if (system === "pal") data[0x24] = 50;

  const vgm = new VGM(data, true);
  const xgm = new XGM(vgm, packed);
  return Uint8Array.from(xgm.asByteArray());
}

/**
 * Emit a ready-to-#include C source for an XGM2 blob: a 256-byte-aligned
 * `const u8 <name>[]` array (the XGM2 data buffer must be 256-aligned in ROM)
 * plus a `<NAME>_LEN` define. Drop it next to your code, `#include` it, and call
 * `XGM2_play(<name>)`.
 *
 * @param {Uint8Array} blob  the XGM2 blob from vgmToXgm2()
 * @param {string} name  C identifier (e.g. "bgm_level1")
 * @returns {string}  C source
 */
export function emitC(blob, name) {
  const upper = name.toUpperCase();
  const lines = [];
  lines.push(`// XGM2 music — generated by romdev-xgm2 (VGM -> XGM2). Play with XGM2_play(${name}).`);
  lines.push(`#define ${upper}_LEN ${blob.length}`);
  lines.push(`const unsigned char ${name}[${blob.length}] __attribute__((aligned(256))) = {`);
  for (let i = 0; i < blob.length; i += 16) {
    const row = [];
    for (let j = i; j < Math.min(i + 16, blob.length); j++) {
      row.push("0x" + (blob[j] & 0xff).toString(16).padStart(2, "0"));
    }
    lines.push("  " + row.join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n") + "\n";
}

/**
 * One-shot convenience: VGM/VGZ -> { blob, cSource }.
 * @param {Uint8Array|Buffer} vgmBytes
 * @param {string} name  C identifier for the emitted array
 * @param {Object} [opts]  passed to vgmToXgm2 (packed/system)
 * @returns {{ blob: Uint8Array, cSource: string, lenDefine: string }}
 */
export function vgmToXgm2C(vgmBytes, name, opts = {}) {
  const blob = vgmToXgm2(vgmBytes, opts);
  return { blob, cSource: emitC(blob, name), lenDefine: `${name.toUpperCase()}_LEN` };
}

export { VGM, XGM };
